;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Item",DevComment="Item Root Tag")
+GameplayTagList=(Tag="Item.Trait",DevComment="Item Trait Root Tag")
+GameplayTagList=(Tag="Item.Type",DevComment="Item Type Root Tag")
+GameplayTagList=(Tag="Item.Type.Dagger",DevComment="Dagger")
+GameplayTagList=(Tag="Skill.Trait.Melee",DevComment="Root Tag for Melee Trait")
+GameplayTagList=(Tag="Skill.Type.Attack",DevComment="Root Tag for Attack Skills")

